version: '3.8'
services:
  # Mysql
  db:
    image: library/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  # Golang
  api:
    container_name: api_web
    environment:
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
      MYSQL_DATABASE: docker_db
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./api_v1:/go/src/api
    ports:
      - 8080:8080
    tty: true
    command: fresh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1           # <= コメントアウトしていない場合はHOSTSの情報を入力する
      - PMA_HOSTS=db
#      - PMA_USER=docker_user     # <= コメントアウトするとログイン画面表示される
#      - PMA_PASSWORD=docker_pass # <= コメントアウトするとログイン画面表示される
    ports:
      - 8888:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions